lst=['apple','banana','pineapple','guava','mango']
print("length of the list: ",len(lst))
print("first element: ", lst[0])
print("last element: ", lst[-1])
lst.append('watermelon')
print("updated list: ", lst)
lst.remove('guava')
print(lst)
lst.sort()
print("sorted list: ", lst)
lst.pop(3)
print(lst)
lst.reverse()
print("reversed list: ", lst)
print ("multiplication of list: ", lst*3)
lst=lst[:3]
print("sliced list: ", lst)
lst.clear()
print("cleared list: ", lst)